DATA = {
    "ACTUATOR": "AN END DEVICE OF A CONTROL SYSTEM, THAT MANIPULATES A PHYSICAL VARIABLE SUCH AS A VALVE OPENING OR POSITION OF A MACHINE PART.",
    "ANTENNA": "A STRUCTURE WHICH CONVERTS BETWEEN ELECTROMAGNETIC WAVES IN SPACE AND CURRENTS IN A CONDUCTOR.",
    "BANDWIDTH": "THE RANGE OF FREQUENCIES OVER WHICH A SYSTEM GENERATES OR USES SIGNIFICANT SIGNAL POWER.",
    "BUSHING": "AN ELECTRICAL FITTING USED TO CONNECT EXTERNAL CONDUCTORS TO THE INTERIOR OF APPARATUS.",
    "CAPACITOR": "AN ELECTRICAL COMPONENT THAT STORES ENERGY IN AN ELECTRIC FIELD.",
    "CATHODE": "THE TERMINAL OF AN ELECTROCHEMICAL OR ELECTRONIC DEVICE FROM WHICH CONVENTIONAL CURRENT EXITS THE DEVICE.",
    "DETECTOR": "A CIRCUIT THAT DEMODULATES A RADIO SIGNAL TO RECOVER INFORMATION.",
    "ELECTRONICS": "THE STUDY OF THE FLOW OF ELECTRONS THROUGH A VACUUM, GASES OR SEMICONDUCTORS.",
    "FEEDBACL": "A SYSTEM THAT SAMPLES PART OF ITS OUTPUT AND ADDS THAT TO ITS INPUT; FEEDBACK MAY BE POSTIVE OR NEGATIVE.",
    "FIRMWARE": "A FORM OF MICRODE OR PROGRAM EMBEDDED INTO HARDWARE DEVICES TO HELP THEM OPERATE EFFECTIVELY.",
    "GENERATOR": "A MACHINE THAT CHANGES MECHANICAL OR CHEMICAL ENERGY INTO ELECTRICAL ENERGY.",
    "HEATSINK": "A STRUCTURE INTENDED TO DISSIPATE HEAT FROM AN ACTIVE DEVICE INTO THE AMBIENT ENVIRONMENT.",
    "INSULATOR": "A SUBSTANCE THAT DOES NOT PERMIT EASY FLOW OF ELECTRICAL CURRENT; A FITTING INTENDED TO SUPPORT A CONDUCTOR.",
    "JITER": "DEVIATION FROM THE TRUE PERIODICITY OF A PERIODIC SIGNAL.",
    "KLYSTRON": "A TYPE OF MICROWAVE OSCILLATOR VACUUM TUBE. IT'S USED IN MANY APPLICATIONS, INCLUDING RADAR, SATELLITE COMMUNICATIONS, AND PARTICLE.",
    "LAN": "LOCAL AREA NETWORK, AN INTERCONNECTION OF COMPUTERS OVER A BUILDING OR SMALL CAMPUS.",
    "MAGNETISM": "THE CLASS OF NATURAL PHENOMENA RELATED TO MAGNETS AND MAGNETIC FIELDS.",
    "MP3": "A STANDARD FOR ENCODING AUDIO IN DIGITAL FORM.",
    "NODE": "A DEFINED POINT IN AN ELECTRICAL NETWORK, WITH SOME POTENTIAL RELATIVE TO A REFERENCE NODE AND WHERE CURRENTS CAN BE SUMMED.",
    "OPTICAL FIBER": "A GLASS OR PLASTIC FIBER USED TO CONVEY SIGNALS TRANSMITTED BY VISIBLE LIGHT OR INFRARED RADIATION.",
    "PHOTOCELL": "A LIGHT SENSOR THAT PRODUCES OR ALTERS A VOLTAGE WHEN LIGHT IS PRESENT.",
    "QUANTIZATION": "ANALOG TO DIGITAL CONVERSION, CHANGING A CONTINUOUSLY VARYING ANALOG SIGNAL TO DISCRETE DIGITAL NUMBERS.",
    "RADAR": "RADIO DETECTION AND RANGING, THE TECHNIQUES FOR OBESERVING THE SPEED AND POSITION OF OBJECTS BY REFLECTED RADIO WAVES.",
    "SATELLITE": "A NATURAL OR ARTIFICIAL OBJECT THAT CIRCLES ANOTHER, BOUND ONLY BY GRAVITY.",
    "TELEGRAPH": "A SYSTEM FOR TRANSMITTING TEXT MESSAGES, BY WIRE OR OTHER MEANS.",
    "TRANSFORMER": "A STATIC ARRANGEMENT OF CONDUCTORS AND POSSIBLY MAGNETIC MATERIALS, THAT TRANSFERS ENERGY BY ELECTROMAGNETIC INDUCTION.",
    "ULTRASOUND": "SOUND HAVING A FREQUENCY ABOVE THE RANGE OF NORMAL HUMAN HEARING. A PORTMANTEAU OF THE FORMER DESCRIPTION OF 'ULTRASONIC SOUND'.",
    "VOLTMETER": "AN INSTRUMENT FOR MEASURING POTENTIAL DIFFERENCE.",
    "WATT": "A UNIT OF MEASUREMENT FOR POWER OR THE RATE OF ENERGY TRANSFER."
    }
a=input("Type a word to define:")
print(DATA[a])
    